# frozen_string_literal: true

namespace :indicator_activity_category do
  desc "Seed standard waste management categories for indicator activities"
  task seed: :environment do
    categories = [
      { name_en: "Waste Generation", name_km: "ការបោះចោលសំណល់", description_en: "Conduct baseline waste assessments; promote waste reduction campaigns; encourage green procurement practices; reduce household waste generation; avoid unnecessary single-use products; conduct waste audits; implement waste minimization measures; adopt sustainable procurement practices; reduce material wastage during operations; use resources efficiently.", description_km: "អនុវត្តការវាយតម្លៃដើមគ្រា អំពីស្ថានភាពសំណល់; លើកកម្ពស់យុទ្ធនាការកាត់បន្ថយសំណល់; ជំរុញការទិញទំនិញ និងសម្ភារៈបរិស្ថាន; កាត់បន្ថយការបង្កើតសំណល់តាមគ្រួសារ; ជៀសវាងការប្រើប្រាស់ផលិតផល (ប្លាស្ទិក) ប្រើតែម្តងដែលមិនចាំបាច់; អនុវត្តសវនកម្មសំណល់; អនុវត្តវិធានការកាត់បន្ថយសំណល់; អនុម័តការអនុវត្តការទិញប្រកបដោយចីរភាព; កាត់បន្ថយការខ្ជះខ្ជាយសម្ភារៈក្នុងប្រតិបត្តិការ; ប្រើប្រាស់ធនធានឱ្យមានប្រសិទ្ធភាព។" },
      { name_en: "Waste Segregation and Storage", name_km: "ការញែកសំណល់ និងរក្សាទុកសំណល់", description_en: "Support source segregation programs; provide guidance on waste separation; facilitate provision of color-coded bins; separate waste into organic, recyclable, residual, and hazardous streams; use designated bins correctly; install labeled waste bins and storage areas; establish segregation procedures; follow waste segregation procedures and use designated containers.", description_km: "គាំទ្រកម្មវិធីញែកសំណល់តាមប្រភព; ផ្តល់ការណែនាំអំពីការញែកសំណល់; សម្របសម្រួលការផ្តល់ធុងសំណល់តាមពណ៌; ញែកសំណល់ជាប្រភេទសរីរាង្គ អាចកែច្នៃឡើងវិញ សំណល់ផ្សេងៗ និងសំណល់គ្រោះថ្នាក់; ប្រើប្រាស់ធុងសំណល់ដែលបានកំណត់ឱ្យត្រឹមត្រូវ; ដាក់ធុងសំណល់ និងកន្លែងស្តុកទុកដែលមានស្លាកសញ្ញាច្បាស់លាស់; បង្កើតនីតិវិធីញែកសំណល់; អនុវត្តតាមនីតិវិធីញែកសំណល់ និងប្រើប្រាស់ធុងដែលបានកំណត់។" },
      { name_en: "Collection", name_km: "ការប្រមូល (សំណល់)", description_en: "Coordinate regular waste collection services; monitor service coverage and performance; place waste at designated collection points according to collection schedules; organize internal waste collection systems and designated storage areas; dispose of waste in designated collection points within the workplace.", description_km: "សម្របសម្រួលសេវាប្រមូលសំណល់ជាប្រចាំ; តាមដានការគ្របដណ្តប់ និងប្រសិទ្ធភាពនៃសេវាប្រមូលសំណល់; ដាក់សំណល់នៅចំណុចប្រមូលដែលបានកំណត់ស្របតាមកាលវិភាគប្រមូល; រៀបចំប្រព័ន្ធប្រមូលសំណល់ផ្ទៃក្នុង និងកន្លែងស្តុកទុកដែលបានកំណត់; បោះចោលសំណល់នៅចំណុចប្រមូលដែលបានកំណត់ក្នុងកន្លែងការងារ។" },
      { name_en: "Transportation", name_km: "ការដឹកជញ្ជូន", description_en: "Coordinate waste transportation services; monitor transportation efficiency and compliance; ensure waste is prepared and accessible for collection; contract licensed waste transport providers; maintain waste transfer records; handle and move waste according to safety procedures.", description_km: "សម្របសម្រួលសេវាដឹកជញ្ជូនសំណល់; តាមដានប្រសិទ្ធភាព និងការអនុលោមតាមបទប្បញ្ញត្តិនៃការដឹកជញ្ជូន; ធានាថាសំណល់ត្រូវបានរៀបចំ និងងាយស្រួលសម្រាប់ការប្រមូល; ចុះកិច្ចសន្យាជាមួយអ្នកដឹកជញ្ជូនសំណល់ដែលមានអាជ្ញាបណ្ណ; រក្សាទុកកំណត់ត្រាដឹកជញ្ជូនសំណល់; គ្រប់គ្រង និងផ្លាស់ទីសំណល់តាមនីតិវិធីសុវត្ថិភាព។" },
      { name_en: "Sorting and Material Recovery", name_km: "ការបែងចែក និងការស្តារសម្ភារៈឡើងវិញ", description_en: "Support establishment of Material Recovery Facilities (MRFs); link recyclers and stakeholders; participate in recycling and material recovery initiatives; establish sorting stations; collaborate with recycling companies and buyers; sort recyclable materials according to workplace guidelines.", description_km: "គាំទ្រការបង្កើតមជ្ឈមណ្ឌលស្តារសម្ភារៈឡើងវិញ (MRF); ភ្ជាប់ទំនាក់ទំនងរវាងអ្នកកែច្នៃឡើងវិញ និងអ្នកពាក់ព័ន្ធ; ចូលរួមក្នុងគំនិតផ្តួចផ្តើមកែច្នៃ និងស្តារសម្ភារៈឡើងវិញ; បង្កើតស្ថានីយបែងចែកសំណល់; សហការជាមួយក្រុមហ៊ុនកែច្នៃ និងអ្នកទិញសម្ភារៈ; តម្រៀបសម្ភារៈដែលអាចកែច្នៃឡើងវិញបានតាមគោលការណ៍ណែនាំកន្លែងការងារ។" },
      { name_en: "Organic Waste Treatment", name_km: "ការព្យាបាលសំណល់សរីរាង្គ", description_en: "Promote community composting programs; identify suitable composting sites; practice household composting and separate organic waste; establish composting systems or organic waste treatment facilities where feasible; separate organic waste from other waste streams.", description_km: "លើកកម្ពស់កម្មវិធីធ្វើជីកំប៉ុសក្នុងសហគមន៍; កំណត់ទីតាំងសមស្របសម្រាប់ការធ្វើជីកំប៉ុស; អនុវត្តការធ្វើជីកំប៉ុសតាមគ្រួសារ និងញែកសំណល់សរីរាង្គ; បង្កើតប្រព័ន្ធធ្វើជីកំប៉ុស ឬមណ្ឌលព្យាបាលសំណល់សរីរាង្គនៅនឹងកន្លែងដែលអាចអនុវត្តបាន; ញែកសំណល់សរីរាង្គចេញពីសំណល់ប្រភេទផ្សេងៗ។" },
      { name_en: "Recycling and Reuse", name_km: "ការកែច្នៃ និងប្រើប្រាស់ឡើងវិញ", description_en: "Facilitate community recycling schemes and market linkages; reuse products and participate in recycling programs; develop recycling partnerships; promote circular economy practices; reuse materials where possible and contribute to recycling efforts.", description_km: "សម្របសម្រួលគម្រោងកែច្នៃឡើងវិញក្នុងសហគមន៍ និងការភ្ជាប់ទីផ្សារ; ប្រើប្រាស់ផលិតផលឡើងវិញ និងចូលរួមក្នុងកម្មវិធីកែច្នៃឡើងវិញ; បង្កើតភាពជាដៃគូក្នុងការកែច្នៃឡើងវិញ; លើកកម្ពស់គោលការណ៍សេដ្ឋកិច្ចវិលជុំ (Circular Economy); ប្រើសម្ភារៈឡើងវិញនៅពេលអាចធ្វើបាន និងរួមចំណែកក្នុងការកែច្នៃឡើងវិញ។" },
      { name_en: "Waste-to-Energy and Alternative Treatment Technologies", name_km: "ការបម្លែងសំណល់ទៅជាថាមពល និងជម្រើសព្យាបាលដោយប្រើបច្ចេកវិទ្យា", description_en: "Facilitate approvals and coordination for appropriate treatment technologies; support environmentally sound treatment initiatives; assess feasibility and invest in suitable treatment technologies; operate treatment equipment in accordance with safety and operational procedures.", description_km: "សម្របសម្រួលការអនុម័ត និងកិច្ចសហការសម្រាប់បច្ចេកវិទ្យាព្យាបាលសមស្រប; គាំទ្រគំនិតផ្តួចផ្តើមព្យាបាលសំណល់ដែលមានសុវត្ថិភាពដល់បរិស្ថាន; វាយតម្លៃលទ្ធភាព និងវិនិយោគលើបច្ចេកវិទ្យាព្យាបាលដែលសមស្រប; ដំណើរការឧបករណ៍ព្យាបាលតាមនីតិវិធីសុវត្ថិភាព និងប្រតិបត្តិការ។" },
      { name_en: "Resource Recovery", name_km: "ការស្តារធនធានឡើងវិញ", description_en: "Support development of resource recovery businesses and recycling markets; sell, donate, or transfer recyclable materials to recovery channels; increase recovery of recyclable materials and strengthen value chains; ensure recoverable materials are properly separated and collected.", description_km: "គាំទ្រការអភិវឌ្ឍអាជីវកម្មស្តារធនធាន និងទីផ្សារកែច្នៃឡើងវិញ; លក់ បរិច្ចាគ ឬផ្ទេរសម្ភារៈដែលអាចស្តារឡើងវិញទៅកាន់បណ្តាញស្តារធនធាន; បង្កើនការស្តារវត្ថុធាតុដែលអាចកែច្នៃឡើងវិញ និងពង្រឹងខ្សែចង្វាក់តម្លៃ; ធានាថាសម្ភារៈដែលអាចស្តារឡើងវិញត្រូវបានញែក និងប្រមូលត្រឹមត្រូវ។" },
      { name_en: "Final Disposal", name_km: "ការបោះចោលចុងក្រោយ", description_en: "Monitor landfill operations; prevent illegal dumping; enforce environmental compliance; dispose of residual waste only through approved systems; ensure waste is disposed of through licensed disposal facilities; follow approved disposal procedures and avoid unauthorized dumping.", description_km: "តាមដានប្រតិបត្តិការទីលានចាក់សំរាម; ទប់ស្កាត់ការបោះចោលសំណល់ខុសច្បាប់; អនុវត្តការអនុលោមតាមស្តង់ដារបរិស្ថាន; បោះចោលសំណល់ផ្សេងៗតាមប្រព័ន្ធដែលបានអនុម័ត; ធានាថាសំណល់ត្រូវបានបោះចោលតាមមណ្ឌលបំផ្លាញសំណល់ដែលមានអាជ្ញាបណ្ណ; អនុវត្តតាមនីតិវិធីបោះចោលដែលបានអនុម័ត និងជៀសវាងការបោះចោលដោយគ្មានការអនុញ្ញាត។" },
      { name_en: "Monitoring, Regulation, and Governance", name_km: "ការតាមដាន បទប្បញ្ញត្តិ និងអភិបាលកិច្ច", description_en: "Develop and enforce local waste management regulations; maintain waste data and reporting systems; comply with waste management regulations and report issues when observed; develop internal waste management policies; maintain monitoring and reporting systems; follow workplace regulations and report non-compliance or incidents.", description_km: "បង្កើត និងអនុវត្តបទប្បញ្ញត្តិគ្រប់គ្រងសំណល់មូលដ្ឋាន; រក្សាប្រព័ន្ធទិន្នន័យ និងរបាយការណ៍សំណល់; អនុលោមតាមបទប្បញ្ញត្តិគ្រប់គ្រងសំណល់ និងរាយការណ៍បញ្ហាដែលបានសង្កេតឃើញ; បង្កើតគោលនយោបាយគ្រប់គ្រងសំណល់ផ្ទៃក្នុង; រក្សាប្រព័ន្ធតាមដាន និងរាយការណ៍; អនុវត្តតាមបទប្បញ្ញត្តិកន្លែងការងារ និងរាយការណ៍អំពីការមិនអនុលោមតាម ឬឧប្បត្តិហេតុ។" },
      { name_en: "Public Awareness and Stakeholder Engagement", name_km: "ការលើកកម្ពស់ការយល់ដឹង និងការចូលរួមរបស់ភាគីពាក់ព័ន្ធ", description_en: "Organize awareness campaigns, consultations, and community meetings; participate in awareness activities, clean-up campaigns, and community initiatives; conduct employee awareness programs and engage with neighboring communities; attend training sessions and promote good waste management practices among peers.", description_km: "រៀបចំយុទ្ធនាការផ្សព្វផ្សាយ ការពិគ្រោះយោបល់ និងកិច្ចប្រជុំសហគមន៍; ចូលរួមក្នុងសកម្មភាពផ្សព្វផ្សាយ យុទ្ធនាការសម្អាតបរិស្ថាន និងគំនិតផ្តួចផ្តើមសហគមន៍; អនុវត្តកម្មវិធីបង្កើនការយល់ដឹងដល់បុគ្គលិក និងចូលរួមជាមួយសហគមន៍ជិតខាង; ចូលរួមវគ្គបណ្តុះបណ្តាល និងលើកកម្ពស់ការអនុវត្តការគ្រប់គ្រងសំណល់ល្អក្នុងចំណោមមិត្តរួមការងារ។" },
      { name_en: "Other", name_km: "ផ្សេងៗ", description_en: "Other activities related to waste management and the circular economy that do not fall under the categories above.", description_km: "សកម្មភាពផ្សេងៗដែលទាក់ទងនឹងការគ្រប់គ្រងសំណល់ និងសេដ្ឋកិច្ចវិលជុំ ដែលមិនស្ថិតក្នុងប្រភេទខាងលើ។" },
      { name_en: "Irrelevant", name_km: "មិនពាក់ព័ន្ធ (Irrelevant)", description_en: "Activities not related to waste management; information or responses unrelated to waste management topics; requests or actions outside the scope of the waste management value chain; data that cannot be classified under any of the categories above; content unrelated to waste reduction, segregation, collection, transportation, recycling, treatment, resource recovery, or disposal.", description_km: "សកម្មភាពដែលមិនទាក់ទងនឹងការគ្រប់គ្រងសំណល់; ព័ត៌មាន ឬការឆ្លើយតបដែលមិនពាក់ព័ន្ធនឹងប្រធានបទសំណល់; សំណើ ឬសកម្មភាពដែលស្ថិតក្រៅវិសាលភាពនៃខ្សែច្រវាក់គ្រប់គ្រងសំណល់; ទិន្នន័យដែលមិនអាចចាត់ចូលក្នុងប្រភេទគ្រប់គ្រងសំណល់ខាងលើបាន; មាតិកាដែលមិនទាក់ទងនឹងការកាត់បន្ថយ ការប្រមូល ការកែច្នៃ ឬការបោះចោលសំណល់។" }
    ]

    categories.each do |attrs|
      category = IndicatorActivityCategory.find_or_initialize_by(name_en: attrs[:name_en])
      category.update!(attrs)
    end
  end
end
