FROM ruby:3.1.3

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs cron \
  wkhtmltopdf \
  xfonts-75dpi \
  xfonts-base

RUN mkdir /app
WORKDIR /app
COPY . /app

RUN bundle install
