FROM ruby:3.1.3

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs \
  wkhtmltopdf \
  xfonts-75dpi \
  xfonts-base

WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN gem install bundler:2.4.10 && bundle install
COPY . .
