{
 "title": "Scorecard Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "province_id",
    "label": "ខេត្ត",
    "query": "select \"name_${locale}\" AS __text, code AS __value  from locations where parent_id is null;"
   },
   {
    "name": "year",
    "label": "ឆ្នាំ",
    "query": "select distinct(year) from scorecards where program_id in (${program_id})"
   },
   {
    "name": "facility_name",
    "label": "សេវា",
    "query": "select name_en from facilities where parent_id is not null AND program_id in (${program_id});"
   },
   {
    "name": "facility_id",
    "label": "Sector",
    "query": "select id AS __value  from facilities where parent_id is not null AND name_en in ($facility_name) AND program_id in (${program_id});"
   },
   {
    "name": "scorecard_type",
    "label": "ប្រភេទប័ណ្ណដាក់ពិន្ទុ",
    "query": "select code AS __value, \"name_${locale}\" AS __text from program_scorecard_types where program_id in (${program_id});"
   },
   {
    "name": "age",
    "label": "Age",
    "query": "< 15 : 0 AND 14, 15 - 30 : 15 AND 30, 31 - 45 : 31 AND 45,  > 45 : 46 AND 99"
   },
   {
    "name": "gender",
    "label": "Gender",
    "query": "Male : male, Female : female, Other : other"
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": "Disability, Minority, ID Poor, Youth"
   },
   {
    "name": "program_id",
    "label": "កម្មវិធី",
    "query": "select name AS __text, id AS __value from programs order by id;"
   },
   {
    "name": "local_ngo_name",
    "label": "Local NGO",
    "query": "select name from local_ngos where deleted_at is null AND program_id in (${program_id});"
   },
   {
    "name": "local_ngo_id",
    "label": "Local NGO",
    "query": "(select id AS __value  from local_ngos where name in ($local_ngo_name) AND deleted_at is null AND program_id in (${program_id})) union all (select -1);"
   },
   {
    "name": "dataset_name",
    "label": "Institution",
    "query": "(SELECT d.name_km FROM datasets d INNER JOIN facilities f ON d.category_id::text = f.category_id::text WHERE f.id IN ($facility_id) AND f.program_id IN (${program_id}) GROUP BY d.name_km) union (SELECT 'មិនកំណត់')"
   },
   {
    "name": "dataset_id",
    "query": "(SELECT d.id::text FROM datasets d INNER JOIN facilities f ON d.category_id::text = f.category_id::text WHERE f.id IN ($facility_id) AND d.name_km IN ($dataset_name) AND f.program_id IN (${program_id}) GROUP BY d.id::text) union all (SELECT '')"
   },
   { "name": "locale", "label": "Language", "query": "ខ្មែរ : km, English : en" },
   {
    "name": "map_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'map_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "summary_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'summary_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_total_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_total_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_total_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_total_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_entered_after_actual_implementation_date_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_entered_after_actual_implementation_date_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_entered_after_actual_implementation_date_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_entered_after_actual_implementation_date_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_duration_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_duration_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_duration_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_duration_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_participants_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_participants_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_participants_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_participants_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_total_indicators_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_total_indicators_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_total_indicators_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_total_indicators_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_average_indicators_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_average_indicators_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_average_indicators_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_average_indicators_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_total_by_service_type_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_total_by_service_type_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_total_by_service_type_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_total_by_service_type_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implemented_by_scorecard_type_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implemented_by_scorecard_type_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implemented_by_scorecard_type_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implemented_by_scorecard_type_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implemented_by_type_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implemented_by_type_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implemented_by_type_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implemented_by_type_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implemented_by_facility_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implemented_by_facility_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implemented_by_facility_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implemented_by_facility_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_by_device_type_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_by_device_type_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_by_device_type_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_by_device_type_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_participants_by_gender_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_participants_by_gender_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_participants_by_gender_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_participants_by_gender_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_participants_by_age_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_participants_by_age_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_participants_by_age_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_participants_by_age_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_participants_by_profile_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_participants_by_profile_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_participants_by_profile_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_participants_by_profile_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_proposed_criteria_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_proposed_criteria_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_proposed_criteria_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_proposed_criteria_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_prioritized_criteria_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_prioritized_criteria_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_prioritized_criteria_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_prioritized_criteria_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_prioritized_criteria_happy_face_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_prioritized_criteria_happy_face_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_prioritized_criteria_happy_face_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_prioritized_criteria_happy_face_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_prioritized_criteria_neutral_face_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_prioritized_criteria_neutral_face_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_prioritized_criteria_neutral_face_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_prioritized_criteria_neutral_face_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_prioritized_criteria_angry_face_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_prioritized_criteria_angry_face_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_top_5_prioritized_criteria_angry_face_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_top_5_prioritized_criteria_angry_face_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_completion_rate_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_completion_rate_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_completion_rate_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_completion_rate_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_geo_coverage_rate_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_geo_coverage_rate_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_geo_coverage_rate_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_geo_coverage_rate_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_beneficiary_reach_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_beneficiary_reach_title'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_beneficiary_reach_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_beneficiary_reach_description'\n  AND locale = '$locale'"
   },
   {
    "name": "data_quality_kpi_panel_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'data_quality_kpi_panel_title'\n  AND locale = '$locale'"
   },
   {
    "name": "data_quality_kpi_panel_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'data_quality_kpi_panel_description'\n  AND locale = '$locale'"
   },
   {
    "name": "fam_reporting_view_by_device_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'fam_reporting_view_by_device_title'\n  AND locale = '$locale'"
   },
   {
    "name": "fam_reporting_view_by_device_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'fam_reporting_view_by_device_description'\n  AND locale = '$locale'"
   },
   {
    "name": "fam_reporting_view_by_detail_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'fam_reporting_view_by_detail_title'\n  AND locale = '$locale'"
   },
   {
    "name": "fam_reporting_view_by_detail_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'fam_reporting_view_by_detail_description'\n  AND locale = '$locale'"
   },
   {
    "name": "num_activities_by_waste_category_title",
    "query": "SELECT label\nFROM translations\nWHERE key = 'num_activities_by_waste_category_title'\n  AND locale = '$locale'"
   },
   {
    "name": "num_activities_by_waste_category_description",
    "query": "SELECT label\nFROM translations\nWHERE key = 'num_activities_by_waste_category_description'\n  AND locale = '$locale'"
   },
   {
    "name": "min_day",
    "query": "SELECT label\nFROM translations\nWHERE key = 'min_day'\n  AND locale = '$locale'"
   },
   {
    "name": "average_day",
    "query": "SELECT label\nFROM translations\nWHERE key = 'average_day'\n  AND locale = '$locale'"
   },
   {
    "name": "max_day",
    "query": "SELECT label\nFROM translations\nWHERE key = 'max_day'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_planned_count",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_planned_count'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implemented_count",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implemented_count'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_type_self_assessment",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_type_self_assessment'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_type_community_scorecard",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_type_community_scorecard'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_type_combined_scorecard",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_type_combined_scorecard'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_device_tablet",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_device_tablet'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_device_mobile",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_device_mobile'\n  AND locale = '$locale'"
   },
   {
    "name": "participant_female",
    "query": "SELECT label\nFROM translations\nWHERE key = 'participant_female'\n  AND locale = '$locale'"
   },
   {
    "name": "participant_male",
    "query": "SELECT label\nFROM translations\nWHERE key = 'participant_male'\n  AND locale = '$locale'"
   },
   {
    "name": "participant_other",
    "query": "SELECT label\nFROM translations\nWHERE key = 'participant_other'\n  AND locale = '$locale'"
   },
   {
    "name": "participant_age",
    "query": "SELECT label\nFROM translations\nWHERE key = 'participant_age'\n  AND locale = '$locale'"
   },
   {
    "name": "participant_id_poor",
    "query": "SELECT label\nFROM translations\nWHERE key = 'participant_id_poor'\n  AND locale = '$locale'"
   },
   {
    "name": "participant_disability",
    "query": "SELECT label\nFROM translations\nWHERE key = 'participant_disability'\n  AND locale = '$locale'"
   },
   {
    "name": "participant_minority",
    "query": "SELECT label\nFROM translations\nWHERE key = 'participant_minority'\n  AND locale = '$locale'"
   },
   {
    "name": "participant_youth",
    "query": "SELECT label\nFROM translations\nWHERE key = 'participant_youth'\n  AND locale = '$locale'"
   },
   {
    "name": "proposed_criteria_count",
    "query": "SELECT label\nFROM translations\nWHERE key = 'proposed_criteria_count'\n  AND locale = '$locale'"
   },
   {
    "name": "selected_criteria_count",
    "query": "SELECT label\nFROM translations\nWHERE key = 'selected_criteria_count'\n  AND locale = '$locale'"
   },
   {
    "name": "vote_count",
    "query": "SELECT label\nFROM translations\nWHERE key = 'vote_count'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_local_ngo",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_local_ngo'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_status",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_status'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_status_planned",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_status_planned'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_status_review",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_status_review'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_status_implemented",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_status_implemented'\n  AND locale = '$locale'"
   },
   {
    "name": "scorecard_implementation_status_rejected",
    "query": "SELECT label\nFROM translations\nWHERE key = 'scorecard_implementation_status_rejected'\n  AND locale = '$locale'"
   },
   {
    "name": "location",
    "query": "SELECT label\nFROM translations\nWHERE key = 'location'\n  AND locale = '$locale'"
   },
   {
    "name": "covered_vs_target",
    "query": "SELECT label\nFROM translations\nWHERE key = 'covered_vs_target'\n  AND locale = '$locale'"
   },
   {
    "name": "coverage_rate",
    "query": "SELECT label\nFROM translations\nWHERE key = 'coverage_rate'\n  AND locale = '$locale'"
   },
   {
    "name": "province_covered",
    "query": "SELECT label\nFROM translations\nWHERE key = 'province_covered'\n  AND locale = '$locale'"
   },
   {
    "name": "district_covered",
    "query": "SELECT label\nFROM translations\nWHERE key = 'district_covered'\n  AND locale = '$locale'"
   },
   {
    "name": "commune_covered",
    "query": "SELECT label\nFROM translations\nWHERE key = 'commune_covered'\n  AND locale = '$locale'"
   },
   {
    "name": "beneficiary_reach",
    "query": "SELECT label\nFROM translations\nWHERE key = 'beneficiary_reach'\n  AND locale = '$locale'"
   },
   {
    "name": "total_participants",
    "query": "SELECT label\nFROM translations\nWHERE key = 'total_participants'\n  AND locale = '$locale'"
   },
   {
    "name": "female_percentage",
    "query": "SELECT label\nFROM translations\nWHERE key = 'female_percentage'\n  AND locale = '$locale'"
   },
   {
    "name": "youth_percentage",
    "query": "SELECT label\nFROM translations\nWHERE key = 'youth_percentage'\n  AND locale = '$locale'"
   },
   {
    "name": "disabilities_percentage",
    "query": "SELECT label\nFROM translations\nWHERE key = 'disabilities_percentage'\n  AND locale = '$locale'"
   },
   {
    "name": "minority_percentage",
    "query": "SELECT label\nFROM translations\nWHERE key = 'minority_percentage'\n  AND locale = '$locale'"
   },
   {
    "name": "total_submitted_scorecard",
    "query": "SELECT label\nFROM translations\nWHERE key = 'total_submitted_scorecard'\n  AND locale = '$locale'"
   },
   {
    "name": "total_approved_scorecard",
    "query": "SELECT label\nFROM translations\nWHERE key = 'total_approved_scorecard'\n  AND locale = '$locale'"
   },
   {
    "name": "total_rejected_scorecard",
    "query": "SELECT label\nFROM translations\nWHERE key = 'total_rejected_scorecard'\n  AND locale = '$locale'"
   },
   {
    "name": "total_custom_indicator_correction",
    "query": "SELECT label\nFROM translations\nWHERE key = 'total_custom_indicator_correction'\n  AND locale = '$locale'"
   },
   {
    "name": "device_type",
    "query": "SELECT label\nFROM translations\nWHERE key = 'device_type'\n  AND locale = '$locale'"
   },
   {
    "name": "os",
    "query": "SELECT label\nFROM translations\nWHERE key = 'os'\n  AND locale = '$locale'"
   },
   {
    "name": "browser",
    "query": "SELECT label\nFROM translations\nWHERE key = 'browser'\n  AND locale = '$locale'"
   },
   {
    "name": "views",
    "query": "SELECT label\nFROM translations\nWHERE key = 'views'\n  AND locale = '$locale'"
   },
   {
    "name": "category_name",
    "query": "SELECT label\nFROM translations\nWHERE key = 'category_name'\n  AND locale = '$locale'"
   },
   {
    "name": "activity_count",
    "query": "SELECT label\nFROM translations\nWHERE key = 'activity_count'\n  AND locale = '$locale'"
   }
  ]
 },
 "panels": [
  {
   "title": "$map_panel_title",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH submitted_scope AS (\n  SELECT s.province_id, s.completed_at, s.rejected_at\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.submitted_at IS NOT NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n),\n\nconducted_by_province AS (\n  SELECT province_id, count(*) AS total_conducted\n  FROM submitted_scope\n  WHERE completed_at IS NOT NULL\n    AND rejected_at IS NULL\n  GROUP BY province_id\n),\n\nin_review_by_province AS (\n  SELECT province_id, count(*) AS total_in_review\n  FROM submitted_scope\n  WHERE completed_at IS NULL\n    AND rejected_at IS NULL\n  GROUP BY province_id\n),\n\nrejected_by_province AS (\n  SELECT province_id, count(*) AS total_rejected\n  FROM submitted_scope\n  WHERE rejected_at IS NOT NULL\n  GROUP BY province_id\n),\n\nplanned_scope AS (\n  SELECT s.province_id, s.local_ngo_id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.created_at)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  concat(\n    '$scorecard_local_ngo (', locations.name_${locale}, ')',\n    '<ol>',\n    array_to_string(array_agg(DISTINCT concat('<li><a href=\"', local_ngos.website_url, '\" target=\"_blank\">', local_ngos.name, '</a></li>')), ''),\n    '</ol>',\n    '<p>',\n    '$scorecard_implementation_status',\n    '<ul>',\n    '<li>$scorecard_implementation_status_planned:<b> ', count(*), '</b></li>',\n    '<li>$scorecard_implementation_status_review:<b> ', COALESCE(max(in_review_by_province.total_in_review), 0), '</b></li>',\n    '<li>$scorecard_implementation_status_implemented:<b> ', COALESCE(max(conducted_by_province.total_conducted), 0), '</b></li>',\n    '<li>$scorecard_implementation_status_rejected:<b> ', COALESCE(max(rejected_by_province.total_rejected), 0), '</b></li>',\n    '</ul>',\n    '</p>'\n  ) AS popup,\n\n  locations.osm_latitude AS latitude,\n  locations.osm_longitude AS longitude,\n\n  concat_ws('/', COALESCE(max(conducted_by_province.total_conducted), 0), count(*)) AS tooltip\n\nFROM planned_scope AS s\nINNER JOIN locations ON s.province_id = locations.code\nINNER JOIN local_ngos ON s.local_ngo_id = local_ngos.id\nLEFT JOIN conducted_by_province ON conducted_by_province.province_id = locations.code\nLEFT JOIN in_review_by_province ON in_review_by_province.province_id = locations.code\nLEFT JOIN rejected_by_province ON rejected_by_province.province_id = locations.code\nGROUP BY\n  locations.name_${locale}, locations.code, locations.latitude, locations.longitude;"
    }
   ]
  },
  {
   "title": "$summary_panel_title",
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 6, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  latitude\nFROM locations\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$scorecard_total_panel_title",
   "type": "stat",
   "description": "$scorecard_total_panel_description",
   "gridPos": { "h": 3, "w": 10, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH scorecards_base AS (\n  SELECT\n    s.*,\n    COALESCE(s.dataset_id::text, '') AS dataset_id2\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n),\n\nconducted_scope AS (\n  SELECT *\n  FROM scorecards_base\n  WHERE $__timeFilter(conducted_date)\n    AND dataset_id2 IN ($dataset_id)\n),\n\nplanned_scope AS (\n  SELECT *\n  FROM scorecards_base\n  WHERE $__timeFilter(created_at)\n    AND dataset_id2 IN ($dataset_id)\n),\n\ntotal_planned AS (\n  SELECT count(*) AS \"Total Planned\"\n  FROM planned_scope\n),\n\ntotal_in_review AS (\n  SELECT count(*) AS \"Total In Review\"\n  FROM conducted_scope\n  WHERE submitted_at IS NOT NULL\n    AND completed_at IS NULL\n    AND rejected_at IS NULL\n),\n\ntotal_conducted AS (\n  SELECT count(*) AS \"Total Conducted\"\n  FROM conducted_scope\n  WHERE completed_at IS NOT NULL OR rejected_at IS NOT NULL\n)\n\nSELECT\n  concat_ws(\n    ' / ',\n    (SELECT * FROM total_planned),\n    (SELECT * FROM total_in_review),\n    (SELECT * FROM total_conducted)\n  ) AS summary"
    }
   ]
  },
  {
   "title": "$scorecard_entered_after_actual_implementation_date_panel_title",
   "type": "stat",
   "description": "$scorecard_entered_after_actual_implementation_date_panel_description",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH scorecards_base AS (\n  SELECT\n    s.*,\n    COALESCE(s.dataset_id::text, '') AS dataset_id2,\n    EXTRACT(epoch FROM (s.finished_date - s.conducted_date)) / 86400 AS conducted_period\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND EXISTS (\n      SELECT 1\n      FROM participants AS p\n      WHERE p.scorecard_uuid = s.id::varchar(20)\n    )\n),\n\ntotal_late_insert AS (\n  SELECT count(*) AS \"Total Conducted\"\n  FROM scorecards_base\n  WHERE completed_at IS NOT NULL\n    AND rejected_at IS NULL\n    AND conducted_period > 0\n    AND dataset_id2 IN ($dataset_id)\n)\n\nSELECT\n  concat_ws(\n    ' / ',\n    (SELECT * FROM total_late_insert)\n  ) AS summary"
    }
   ]
  },
  {
   "title": "$scorecard_completion_rate_panel_title",
   "type": "stat",
   "description": "$scorecard_completion_rate_panel_description",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH scorecards_base AS (\n  SELECT\n    s.*,\n    COALESCE(s.dataset_id::text, '') AS dataset_id2\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n),\n\nconducted_scope AS (\n  SELECT *\n  FROM scorecards_base\n  WHERE $__timeFilter(conducted_date)\n    AND dataset_id2 IN ($dataset_id)\n),\n\nplanned_scope AS (\n  SELECT *\n  FROM scorecards_base\n  WHERE $__timeFilter(created_at)\n    AND dataset_id2 IN ($dataset_id)\n),\n\ntotal_conducted AS (\n  SELECT count(*) AS total_conducted\n  FROM conducted_scope\n  WHERE completed_at IS NOT NULL\n),\n\ntotal_planned AS (\n  SELECT count(*) AS total_planned\n  FROM planned_scope\n)\n\nSELECT\n  concat(\n    ROUND(\n      (SELECT total_conducted FROM total_conducted)::numeric\n      / NULLIF((SELECT total_planned FROM total_planned), 0) * 100,\n      2\n    ),\n    '%'\n  ) AS \"Completion Rate\""
    }
   ]
  },
  {
   "title": "$scorecard_geo_coverage_rate_panel_title",
   "type": "table",
   "description": "$scorecard_geo_coverage_rate_panel_description",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH covered_locations AS (\n  SELECT DISTINCT\n    d.province_id,\n    d.district_id,\n    d.commune_id\n  FROM scorecards AS s\n  INNER JOIN datasets AS d ON s.dataset_id = d.id\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND d.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n),\n\ntarget_locations AS (\n  SELECT DISTINCT\n    d.province_id,\n    d.district_id,\n    d.commune_id\n  FROM scorecards AS s\n  INNER JOIN datasets AS d ON s.dataset_id = d.id\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.created_at)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND d.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.rejected_at IS NULL\n),\n\nsummary AS (\n  SELECT\n    (SELECT count(DISTINCT province_id) FROM covered_locations) AS provinces_covered,\n    (SELECT count(DISTINCT province_id) FROM target_locations) AS provinces_target,\n    (SELECT count(DISTINCT district_id) FROM covered_locations) AS districts_covered,\n    (SELECT count(DISTINCT district_id) FROM target_locations) AS districts_target,\n    (SELECT count(DISTINCT commune_id) FROM covered_locations) AS communes_covered,\n    (SELECT count(DISTINCT commune_id) FROM target_locations) AS communes_target\n)\n\nSELECT '$province_covered' AS \"$location\",\n  concat(provinces_covered, '/', provinces_target) AS \"$covered_vs_target\",\n  concat(ROUND((provinces_covered::numeric / NULLIF(provinces_target, 0)) * 100, 2), '%') AS \"$coverage_rate\"\nFROM summary\n\nUNION ALL\n\nSELECT '$district_covered' AS \"$location\",\n  concat(districts_covered, '/', districts_target) AS \"$covered_vs_target\",\n  concat(ROUND((districts_covered::numeric / NULLIF(districts_target, 0)) * 100, 2), '%') AS \"$coverage_rate\"\nFROM summary\n\nUNION ALL\n\nSELECT '$commune_covered' AS \"$location\",\n  concat(communes_covered, '/', communes_target) AS \"$covered_vs_target\",\n  concat(ROUND((communes_covered::numeric / NULLIF(communes_target, 0)) * 100, 2), '%') AS \"$coverage_rate\"\nFROM summary"
    }
   ]
  },
  {
   "title": "$scorecard_implementation_duration_panel_title",
   "type": "stat",
   "description": "$scorecard_implementation_duration_panel_description",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT\n    CEIL(\n      EXTRACT(epoch FROM (s.completed_at - s.conducted_date)) / 86400 * 2\n    ) / 2 AS duration\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  min(duration)::integer AS \"$min_day\",\n  avg(duration)::integer AS \"$average_day\",\n  max(duration)::integer AS \"$max_day\"\nFROM conducted_scope;"
    }
   ]
  },
  {
   "title": "$data_quality_kpi_panel_title",
   "type": "table",
   "description": "$data_quality_kpi_panel_description",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws(\n      '',\n      (CASE WHEN s.dataset_id IS NULL THEN '' END),\n      (CASE WHEN s.dataset_id IS NOT NULL THEN s.dataset_id END)\n    ) AS dataset_id2\n  FROM scorecards AS s\n  WHERE \n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.created_at)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n),\n\n_filtered_scorecards AS (\n  SELECT s.*\n  FROM _scorecards s\n  WHERE s.dataset_id2 IN ($dataset_id)\n),\n\n_total_submitted AS (\n  SELECT count(*) AS total_submitted\n  FROM _filtered_scorecards\n  WHERE submitted_at IS NOT NULL\n),\n\n_total_approved AS (\n  SELECT count(*) AS total_approved\n  FROM _filtered_scorecards\n  WHERE completed_at IS NOT NULL\n),\n\n_total_rejected AS (\n  SELECT count(*) AS total_rejected\n  FROM _filtered_scorecards\n  WHERE rejected_at IS NOT NULL\n),\n\n_total_custom_indicator_correction AS (\n  SELECT count(*) AS total_custom_indicator_correction\n  FROM raised_indicators AS ri\n  INNER JOIN indicators AS i ON ri.indicator_uuid = i.uuid\n  INNER JOIN _filtered_scorecards AS s ON ri.scorecard_uuid = s.id::varchar(20)\n  WHERE \n    i.type = 'Indicators::CustomIndicator'\n    AND ri.updated_at > ri.created_at\n)\n\nSELECT\n  (SELECT total_submitted FROM _total_submitted) AS \"$total_submitted_scorecard\",\n  (SELECT total_approved FROM _total_approved) AS \"$total_approved_scorecard\",\n  (SELECT total_rejected FROM _total_rejected) AS \"$total_rejected_scorecard\",\n  (SELECT total_custom_indicator_correction FROM _total_custom_indicator_correction) AS \"$total_custom_indicator_correction\""
    }
   ]
  },
  {
   "title": "$scorecard_beneficiary_reach_title",
   "type": "table",
   "description": "$scorecard_beneficiary_reach_description",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH scorecards_base AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n),\n\nparticipants_scope AS (\n  SELECT p.*\n  FROM participants AS p\n  WHERE p.countable = true\n    AND p.scorecard_uuid::integer IN (SELECT id FROM scorecards_base)\n),\n\ntotals AS (\n  SELECT\n    count(*) AS total_participant,\n    count(*) FILTER (WHERE gender = 'female') AS total_female,\n    count(*) FILTER (WHERE youth = true)      AS total_youth,\n    count(*) FILTER (WHERE disability = true) AS total_disability,\n    count(*) FILTER (WHERE minority = true)   AS total_minority\n  FROM participants_scope\n)\n\nSELECT\n  total_participant AS \"$total_participants\",\n  concat(total_female, ' (', ROUND(total_female::numeric / NULLIF(total_participant, 0) * 100, 0), '%)') AS \"$female_percentage\",\n  concat(total_youth, ' (', ROUND(total_youth::numeric / NULLIF(total_participant, 0) * 100, 0), '%)') AS \"$youth_percentage\",\n  concat(total_disability, ' (', ROUND(total_disability::numeric / NULLIF(total_participant, 0) * 100, 0), '%)') AS \"$disabilities_percentage\",\n  concat(total_minority, ' (', ROUND(total_minority::numeric / NULLIF(total_participant, 0) * 100, 0), '%)') AS \"$minority_percentage\"\nFROM totals;"
    }
   ]
  },
  {
   "title": "$fam_reporting_view_by_device_title",
   "type": "piechart",
   "description": "$fam_reporting_view_by_device_description",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  v.device_type,\n  COUNT(*) AS views\nFROM ahoy_events e\nJOIN ahoy_visits v ON v.id = e.visit_id\nWHERE e.name = 'view_fam_reporting'\n  AND $__timeFilter(e.time)\nGROUP BY v.device_type;"
    }
   ]
  },
  {
   "title": "$fam_reporting_view_by_detail_title",
   "type": "table",
   "description": "$fam_reporting_view_by_detail_description",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  v.device_type as \"$device_type\",\n  v.os as \"$os\",\n  v.browser as \"$browser\",\n  COUNT(*) AS \"$views\"\nFROM ahoy_events e\nJOIN ahoy_visits v ON v.id = e.visit_id\nWHERE e.name = 'view_fam_reporting'\n  AND $__timeFilter(e.time)\nGROUP BY 1, 2, 3\nORDER BY 4 DESC;"
    }
   ]
  },
  {
   "title": "$scorecard_participants_panel_title",
   "type": "stat",
   "description": "$scorecard_participants_panel_description",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH scorecards_base AS (\n  SELECT\n    s.*,\n    COALESCE(s.dataset_id::text, '') AS dataset_id2\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.rejected_at is NULL\n),\n\nconducted_scope AS (\n  SELECT *\n  FROM scorecards_base\n  WHERE $__timeFilter(conducted_date)\n    AND completed_at IS NOT NULL\n    AND dataset_id2 IN ($dataset_id)\n),\n\nplanned_scope AS (\n  SELECT *\n  FROM scorecards_base\n  WHERE $__timeFilter(created_at)\n    AND dataset_id2 IN ($dataset_id)\n),\n\ntotal_lngo AS (\n  SELECT count(DISTINCT local_ngo_id) AS total_lngo\n  FROM planned_scope\n),\n\ntotal_caf AS (\n  SELECT count(*) AS total_caf\n  FROM cafs\n  WHERE local_ngo_id IN (SELECT local_ngo_id FROM planned_scope)\n),\n\ntotal_participant AS (\n  SELECT count(*) AS total_participant\n  FROM participants\n  WHERE scorecard_uuid::integer IN (SELECT id FROM conducted_scope)\n),\n\navg_participant AS (\n  SELECT COALESCE(\n    (SELECT total_participant FROM total_participant)\n    / NULLIF((SELECT count(*) FROM conducted_scope), 0),\n    0\n  ) AS avg_participant\n)\n\nSELECT\n  concat_ws(\n    ' / ',\n    (SELECT total_lngo FROM total_lngo),\n    (SELECT total_caf FROM total_caf),\n    (SELECT total_participant FROM total_participant),\n    (SELECT avg_participant FROM avg_participant)\n  ) AS summary;"
    }
   ]
  },
  {
   "title": "$scorecard_total_indicators_panel_title",
   "type": "stat",
   "description": "$scorecard_total_indicators_panel_description",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH raised AS (\n  SELECT\n    ri.indicator_uuid,\n    ri.selected,\n    ri.scorecard_uuid,\n    i.type\n  FROM raised_indicators AS ri\n  INNER JOIN indicators AS i ON ri.indicator_uuid = i.uuid\n),\n\ncompleted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n),\n\nraised_scope AS (\n  SELECT raised.indicator_uuid, raised.scorecard_uuid, raised.type, raised.selected\n  FROM raised\n  INNER JOIN completed_scope ON raised.scorecard_uuid::integer = completed_scope.id\n),\n\ntotals AS (\n  SELECT\n    count(DISTINCT (indicator_uuid, scorecard_uuid)) AS total_raised,\n    count(DISTINCT (indicator_uuid, scorecard_uuid))\n      FILTER (WHERE type = 'Indicators::CustomIndicator') AS total_raised_custom,\n    count(DISTINCT (indicator_uuid, scorecard_uuid))\n      FILTER (WHERE selected = true) AS total_raised_selected\n  FROM raised_scope\n)\n\nSELECT\n  concat_ws(' / ', total_raised, total_raised_custom, total_raised_selected) AS summary\nFROM totals;"
    }
   ]
  },
  {
   "title": "$scorecard_average_indicators_panel_title",
   "type": "stat",
   "description": "$scorecard_average_indicators_panel_description",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH raised AS (\n  SELECT\n    ri.indicator_uuid,\n    ri.selected,\n    ri.scorecard_uuid,\n    i.type\n  FROM raised_indicators AS ri\n  INNER JOIN indicators AS i ON ri.indicator_uuid = i.uuid\n),\n\ncompleted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n),\n\nraised_scope AS (\n  SELECT raised.indicator_uuid, raised.scorecard_uuid, raised.type, raised.selected\n  FROM raised\n  INNER JOIN completed_scope ON raised.scorecard_uuid::integer = completed_scope.id\n),\n\ntotals AS (\n  SELECT\n    (SELECT count(*) FROM completed_scope) AS total_scorecard,\n    count(DISTINCT (indicator_uuid, scorecard_uuid)) AS total_raised,\n    count(DISTINCT (indicator_uuid, scorecard_uuid))\n      FILTER (WHERE selected = true) AS total_raised_selected,\n    count(DISTINCT (indicator_uuid, scorecard_uuid))\n      FILTER (WHERE type = 'Indicators::CustomIndicator') AS total_raised_custom\n  FROM raised_scope\n)\n\nSELECT\n  concat_ws(\n    ' / ',\n    COALESCE(CEIL(total_raised::numeric / NULLIF(total_scorecard, 0)), 0),\n    COALESCE(CEIL(total_raised_custom::numeric / NULLIF(total_scorecard, 0)), 0),\n    COALESCE(CEIL(total_raised_selected::numeric / NULLIF(total_scorecard, 0)), 0)\n  ) AS summary\nFROM totals;"
    }
   ]
  },
  {
   "title": "$scorecard_total_by_service_type_panel_title",
   "type": "barchart",
   "description": "$scorecard_total_by_service_type_panel_description",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "WITH scorecards_base AS (\n  SELECT\n    s.*,\n    COALESCE(s.dataset_id::text, '') AS dataset_id2\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.rejected_at IS NULL\n),\n\nconducted_scope AS (\n  SELECT *\n  FROM scorecards_base\n  WHERE $__timeFilter(conducted_date)\n    AND completed_at IS NOT NULL\n    AND dataset_id2 IN ($dataset_id)\n),\n\nplanned_scope AS (\n  SELECT *\n  FROM scorecards_base\n  WHERE $__timeFilter(created_at)\n    AND facility_id IN ($facility_id)\n    AND dataset_id2 IN ($dataset_id)\n),\n\nplanned_by_facility AS (\n  SELECT facility_id, count(*) AS total_planned\n  FROM planned_scope\n  GROUP BY facility_id\n),\n\nconducted_by_facility AS (\n  SELECT facility_id, count(*) AS total_conducted\n  FROM conducted_scope\n  GROUP BY facility_id\n)\n\nSELECT\n  facilities.name_${locale} AS name,\n  sum(COALESCE(planned_by_facility.total_planned, 0)) AS \"$scorecard_planned_count\",\n  sum(COALESCE(conducted_by_facility.total_conducted, 0)) AS \"$scorecard_implemented_count\"\nFROM planned_by_facility\nINNER JOIN facilities ON planned_by_facility.facility_id = facilities.id\nLEFT JOIN conducted_by_facility ON conducted_by_facility.facility_id = facilities.id\nGROUP BY facilities.name_${locale};"
    }
   ]
  },
  {
   "title": "$scorecard_implemented_by_scorecard_type_panel_title",
   "type": "barchart",
   "description": "$scorecard_implemented_by_scorecard_type_panel_description",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.*\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  facilities.name_${locale} AS name,\n  count(*) FILTER (WHERE conducted_scope.scorecard_type = 1) AS \"$scorecard_type_self_assessment\",\n  count(*) FILTER (WHERE conducted_scope.scorecard_type = 2) AS \"$scorecard_type_community_scorecard\",\n  count(*) FILTER (WHERE conducted_scope.scorecard_type = 3) AS \"$scorecard_type_combined_scorecard\"\nFROM conducted_scope\nINNER JOIN facilities ON conducted_scope.facility_id = facilities.id\nGROUP BY facilities.name_${locale};"
    }
   ]
  },
  {
   "title": "$scorecard_implemented_by_type_panel_title",
   "type": "piechart",
   "description": "$scorecard_implemented_by_type_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT\n    s.*,\n    CASE s.scorecard_type\n      WHEN 1 THEN '$scorecard_type_self_assessment'\n      WHEN 2 THEN '$scorecard_type_community_scorecard'\n      WHEN 3 THEN '$scorecard_type_combined_scorecard'\n    END AS scorecard_type_km\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  scorecard_type_km,\n  count(*)\nFROM conducted_scope\nGROUP BY scorecard_type_km;"
    }
   ]
  },
  {
   "title": "$scorecard_implemented_by_facility_panel_title",
   "type": "piechart",
   "description": "$scorecard_implemented_by_facility_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.*\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  facilities.name_${locale} AS name,\n  count(*)\nFROM conducted_scope\nINNER JOIN facilities ON conducted_scope.facility_id = facilities.id\nGROUP BY facilities.name_${locale};"
    }
   ]
  },
  {
   "title": "$scorecard_implementation_by_device_type_panel_title",
   "type": "piechart",
   "description": "$scorecard_implementation_by_device_type_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.*\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  CASE\n    WHEN device_type = 'mobile' THEN '$scorecard_device_mobile'\n    ELSE '$scorecard_device_tablet'\n  END AS \"device_type\",\n  count(*)\nFROM conducted_scope\nGROUP BY device_type;"
    }
   ]
  },
  {
   "title": "$scorecard_participants_by_gender_panel_title",
   "type": "piechart",
   "description": "$scorecard_participants_by_gender_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  CASE\n    WHEN gender = 'male' THEN '$participant_male'\n    WHEN gender = 'female' THEN '$participant_female'\n    ELSE '$participant_other'\n  END AS gender_km,\n  count(*)\nFROM participants AS p\nWHERE p.countable = true\n  AND EXISTS (\n    SELECT 1 FROM conducted_scope AS cs WHERE cs.id = p.scorecard_uuid::integer\n  )\nGROUP BY gender_km\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "$scorecard_participants_by_age_panel_title",
   "type": "piechart",
   "description": "$scorecard_participants_by_age_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  CASE\n    WHEN age > 45 THEN '$participant_age > 45'\n    WHEN age > 30 THEN '$participant_age 31 - 45'\n    WHEN age > 14 THEN '$participant_age 15 - 30'\n    ELSE '$participant_age< 15'\n  END AS age_range,\n  count(*)\nFROM participants AS p\nWHERE p.countable = true\n  AND EXISTS (\n    SELECT 1 FROM conducted_scope AS cs WHERE cs.id = p.scorecard_uuid::integer\n  )\nGROUP BY age_range\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "$scorecard_participants_by_profile_panel_title",
   "type": "barchart",
   "description": "$scorecard_participants_by_profile_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n),\n\npar AS (\n  SELECT p.gender, v.profile_locale\n  FROM participants AS p\n  INNER JOIN conducted_scope AS cs ON p.scorecard_uuid = cs.id::varchar(255)\n  CROSS JOIN LATERAL (\n    VALUES\n      ('$participant_id_poor', p.poor_card),\n      ('$participant_disability', p.disability),\n      ('$participant_minority', p.minority),\n      ('$participant_youth', p.youth)\n  ) AS v(profile_locale, flag)\n  WHERE v.flag\n)\n\nSELECT\n  profile_locale,\n  SUM(CASE WHEN gender = 'female' THEN 1 END) AS \"$participant_female\",\n  SUM(CASE WHEN gender = 'male' THEN 1 END) AS \"$participant_male\",\n  SUM(CASE WHEN gender = 'other' THEN 1 END) AS \"$participant_other\"\nFROM par\nGROUP BY profile_locale;"
    }
   ]
  },
  {
   "title": "$scorecard_top_5_proposed_criteria_panel_title",
   "type": "barchart",
   "description": "$scorecard_top_5_proposed_criteria_panel_description",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  indicators.name,\n  count(*) AS \"$proposed_criteria_count\"\nFROM raised_indicators\nINNER JOIN conducted_scope ON raised_indicators.scorecard_uuid::integer = conducted_scope.id\nINNER JOIN indicators ON raised_indicators.indicator_uuid = indicators.uuid\nGROUP BY indicators.name\nORDER BY \"$proposed_criteria_count\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "$scorecard_top_5_prioritized_criteria_panel_title",
   "type": "barchart",
   "description": "$scorecard_top_5_prioritized_criteria_panel_description",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  indicators.name,\n  count(DISTINCT raised_indicators.scorecard_uuid) AS \"$selected_criteria_count\"\nFROM raised_indicators\nINNER JOIN conducted_scope ON raised_indicators.scorecard_uuid::integer = conducted_scope.id\nINNER JOIN indicators ON raised_indicators.indicator_uuid = indicators.uuid\nWHERE raised_indicators.selected IS true\nGROUP BY indicators.name\nORDER BY \"$selected_criteria_count\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "$scorecard_top_5_prioritized_criteria_happy_face_panel_title",
   "type": "barchart",
   "description": "$scorecard_top_5_prioritized_criteria_happy_face_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  indicators.name,\n  count(*) AS \"$vote_count\"\nFROM ratings\nINNER JOIN voting_indicators ON voting_indicators.uuid = ratings.voting_indicator_uuid\nINNER JOIN indicators ON voting_indicators.indicator_uuid = indicators.uuid\nINNER JOIN conducted_scope ON voting_indicators.scorecard_uuid::integer = conducted_scope.id\nWHERE ratings.score > 3\nGROUP BY indicators.name\nORDER BY \"$vote_count\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "$scorecard_top_5_prioritized_criteria_neutral_face_panel_title",
   "type": "barchart",
   "description": "$scorecard_top_5_prioritized_criteria_neutral_face_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  indicators.name,\n  count(*) AS \"$vote_count\"\nFROM ratings\nINNER JOIN voting_indicators ON voting_indicators.uuid = ratings.voting_indicator_uuid\nINNER JOIN indicators ON voting_indicators.indicator_uuid = indicators.uuid\nINNER JOIN conducted_scope ON voting_indicators.scorecard_uuid::integer = conducted_scope.id\nWHERE ratings.score = 3\nGROUP BY indicators.name\nORDER BY \"$vote_count\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "$scorecard_top_5_prioritized_criteria_angry_face_panel_title",
   "type": "barchart",
   "description": "$scorecard_top_5_prioritized_criteria_angry_face_panel_description",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "rawSql": "WITH conducted_scope AS (\n  SELECT s.id\n  FROM scorecards AS s\n  WHERE\n    s.program_id IN (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type IN ($scorecard_type)\n    AND s.year IN ($year)\n    AND s.facility_id IN ($facility_id)\n    AND s.province_id IN ($province_id)\n    AND s.local_ngo_id IN ($local_ngo_id)\n    AND s.deleted_at IS NULL\n    AND s.completed_at IS NOT NULL\n    AND s.rejected_at IS NULL\n    AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n)\n\nSELECT\n  indicators.name,\n  count(*) AS \"$vote_count\"\nFROM ratings\nINNER JOIN voting_indicators ON voting_indicators.uuid = ratings.voting_indicator_uuid\nINNER JOIN indicators ON voting_indicators.indicator_uuid = indicators.uuid\nINNER JOIN conducted_scope ON voting_indicators.scorecard_uuid::integer = conducted_scope.id\nWHERE ratings.score < 3\nGROUP BY indicators.name\nORDER BY \"$vote_count\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "$num_activities_by_waste_category_title",
   "type": "barchart",
   "description": "$num_activities_by_waste_category_description",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "WITH filtered_scorecards AS (\n    SELECT s.uuid\n    FROM scorecards AS s\n    WHERE s.program_id IN (${program_id})\n      AND $__timeFilter(s.conducted_date)\n      AND s.scorecard_type IN ($scorecard_type)\n      AND s.year IN ($year)\n      AND s.facility_id IN ($facility_id)\n      AND s.province_id IN ($province_id)\n      AND s.local_ngo_id IN ($local_ngo_id)\n      AND s.deleted_at IS NULL\n      AND s.completed_at IS NOT NULL\n      AND s.rejected_at IS NULL\n      AND COALESCE(s.dataset_id::text, '') IN ($dataset_id)\n  )\n\n  SELECT\n    cate.name_${locale} AS \"$category_name\",\n    count(*) AS \"$activity_count\"\n  FROM indicator_activities ia\n  INNER JOIN filtered_scorecards sc ON ia.scorecard_uuid = sc.uuid\n  INNER JOIN indicator_activity_categories cate ON ia.indicator_activity_category_id = cate.id\n  GROUP BY cate.id, \"$category_name\"\n  ORDER BY \"$activity_count\" DESC;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 84 },
   "options": {
    "content": "<div style=\"font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 32px 16px;\">\n\n  <!-- Version 2 (2025) -->\n  <div style=\"text-align: center; margin-bottom: 24px;\">\n    <div style=\"font-size: 14px; font-weight: 500; color: #1a1a1a; line-height: 1.6;\">\n      កំណែទី២ (ឆ្នាំ២០២៥)៖ សហការផលិតដោយ\n    </div>\n    <div style=\"font-size: 14px; font-weight: 500; color: #1a1a1a; line-height: 1.6;\">\n      Version 2 (2025), Co-produced by\n    </div>\n  </div>\n\n  <div style=\"display: flex; justify-content: center; flex-wrap: wrap; gap: 48px; padding-bottom: 40px; border-bottom: 1px solid #e5e5e5;\">\n\n    <div style=\"text-align: center;\">\n      <h5 style=\"font-size: 14px; font-weight: 500; color: #444; margin: 0 0 16px 0;\">\n        សហការគាំទ្រមូលនិធិដោយ/Co-funded by:\n      </h5>\n      <div style=\"display: flex; align-items: center; justify-content: center; gap: 20px;\">\n        <img src=\"https://digitalscorecard.org/assets/stakeholder_v2/eu-4214c5869a64c511e3308e315b75cf72bbe5aa8eafb292caeabf08269b829ea6.png\" height=\"56\" style=\"display: block;\"/>\n        <img src=\"https://digitalscorecard.org/assets/stakeholder_v2/ipa-337739219cc18f911825f4a31eb5f6acf685986a268920d06b0b731885887e87.png\" height=\"48\" style=\"display: block;\"/>\n      </div>\n    </div>\n\n    <div style=\"text-align: center;\">\n      <h5 style=\"font-size: 14px; font-weight: 500; color: #444; margin: 0 0 16px 0;\">\n        សហការអនុវត្តដោយ/Co-implemented by:\n      </h5>\n      <div style=\"display: flex; align-items: center; justify-content: center; gap: 20px;\">\n        <img src=\"https://digitalscorecard.org/assets/stakeholder_v2/care-833e9065d49ba3c7c0b47f0a3291821873edbfc3c65c4047c3db6cd28e63b9b0.png\" height=\"36\" style=\"display: block;\"/>\n        <img src=\"https://digitalscorecard.org/assets/stakeholder_v2/ycc-073d5f1f4b2f67648e7ea81fd92999ca4a214ce36d77395168f7b1237c9ed940.png\" height=\"40\" style=\"display: block;\"/>\n        <img src=\"https://digitalscorecard.org/assets/stakeholder_v2/idea-eb888e696eb1697652332068774e3191fd757a91a4721a839cbf394982c39e4a.jpg\" height=\"36\" style=\"display: block;\"/>\n      </div>\n    </div>\n\n  </div>\n\n  <!-- Version 1 -->\n  <div style=\"text-align: center; margin-top: 40px; margin-bottom: 24px;\">\n    <div style=\"font-size: 14px; font-weight: 500; color: #1a1a1a; line-height: 1.6;\">\n      កំណែទី១៖ សហការផលិតដោយ\n    </div>\n    <div style=\"font-size: 14px; font-weight: 500; color: #1a1a1a; line-height: 1.6;\">\n      Version 1, Co-produced by\n    </div>\n  </div>\n\n  <div style=\"display: flex; justify-content: center; flex-wrap: wrap; gap: 56px; padding-bottom: 8px;\">\n\n    <div style=\"text-align: center;\">\n      <p style=\"font-size: 14px; font-weight: 500; color: #444; margin: 0 0 16px 0;\">\n        គាំទ្រមូលនិធិដោយ / Funded by\n      </p>\n      <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://eeas.europa.eu/delegations/cambodia_en\" style=\"display: inline-block;\">\n        <img alt=\"EU Cambodia\" src=\"https://digitalscorecard.org/assets/eu-3902d24e7e972494ede15c7dc533bc20589ef6e80aca3335518cea5944984c09.png\" height=\"56\" style=\"display: block;\"/>\n      </a>\n    </div>\n\n    <div style=\"text-align: center;\">\n      <p style=\"font-size: 14px; font-weight: 500; color: #444; margin: 0 0 16px 0;\">\n        អនុវត្តដោយ / Implemented by\n      </p>\n      <div style=\"display: flex; align-items: center; justify-content: center; flex-wrap: wrap; gap: 20px;\">\n        <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.care-cambodia.org/\" style=\"display: inline-block;\">\n          <img alt=\"Care\" src=\"https://digitalscorecard.org/assets/care_logo-30bc7807ccb532ee750d35b55a3e94c40e688a88a18d0497c4e244bc56f4017d.png\" height=\"36\" style=\"display: block;\"/>\n        </a>\n        <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://apiinstitute.org/\" style=\"display: inline-block;\">\n          <img alt=\"API\" src=\"https://digitalscorecard.org/assets/api-a84a9246854e6e9c471aa6982fb90ed27377b050f69318966fe0c3923d371886.png\" height=\"36\" style=\"display: block;\"/>\n        </a>\n        <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"http://ilabsoutheastasia.org\" style=\"display: inline-block;\">\n          <img alt=\"InSTEDD iLabSEA\" src=\"https://digitalscorecard.org/assets/instedd-ilabsea-252db350ccbce84ff56c4057db2f6a5761873c8d7b4c9c5ee9c31049ba7d3792.png\" height=\"36\" style=\"display: block;\"/>\n        </a>\n      </div>\n    </div>\n\n  </div>\n\n  <!-- About Us -->\n  <div style=\"text-align: center; margin-top: 40px;\">\n    <a href=\"https://digitalscorecard.org/about\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"font-size: 14px; font-weight: 500; color: #0066cc; text-decoration: none;\">\n      អំពីយើង / About Us\n    </a>\n  </div>\n\n</div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  latitude\nFROM locations\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  }
 ]
}